version: "3"
services:
  dhcp-api:
    image: kerwood/isc-dhcp-api
    container_name: isc-dhcp-api
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./dhcpd.conf:/dhcpd/dhcpd.conf
      - ./dhcpd.leases:/dhcpd/dhcpd.leases
