version: "3"
services:
  dhcp-api:
    image: kerwood/isc-dhcp-api
    container_name: isc-dhcp-api
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /etc/dhcp/:/dhcpd-config # isc-dhcp config directory
      - /var/lib/dhcp/:/dhcpd-leases # isc-dhcp leases directory